version: '3.8'
services:
  backend:
    image: local/gametracker-backend:staging
    pull_policy: never
    ports:
      - "3001:3000"
    volumes:
      - /home/docker/gametracker/data-stag/gametracker.db:/app/gametracker.db
      - /home/docker/gametracker/data-stag/settings.json:/app/settings.json
      - /home/docker/gametracker/data-stag/sent_notifications.json:/app/sent_notifications.json
    environment:
      - NODE_ENV=staging
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_BEARER_TOKEN=${IGDB_BEARER_TOKEN}
      - RAWG_API_KEY=${RAWG_API_KEY}
      - JWT_SECRET=${JWT_SECRET:-supersecretkey}
    restart: unless-stopped

  frontend:
    image: local/gametracker-frontend:staging
    pull_policy: never
    ports:
      - "8085:80"
    restart: unless-stopped


