-- 001_initial_schema.sql
--
-- The complete GameTracker schema, translated from the SQLite original.
-- Applied inside a transaction by schema-migrate.js. If any statement in this
-- file fails, the whole migration rolls back and the backend refuses to boot --
-- which is the entire point. The SQLite version swallowed migration errors and
-- silently shipped installs missing four columns.
--
-- TYPE DECISIONS (each one deliberate -- see PRODUCTION_CHANGELOG.txt):
--
--   game_id is TEXT, NOT INTEGER.
--     The SQLite column was *declared* INTEGER but every row stores a string:
--     all 379 production rows are values like 'igdb_19564'. SQLite's flexible
--     typing allowed it; Postgres would reject every insert. TEXT is the only
--     correct type here. Verified against the live database before writing this.
--
--   Booleans stay INTEGER (0/1), dates stay TEXT.
--     Both are tempting to "fix". Both are load-bearing: can_manage_users and
--     shares_library are truth-tested in dozens of places across backend AND
--     frontend, and created_at / release_date / last_price_updated are consumed
--     as ISO strings by the frontend and the Android client. Converting them is
--     a behaviour change, not a port, and belongs in its own reviewable commit.
--
--   notification_days stays TEXT holding a JSON array string, e.g. '[0,7,30]'.
--     JSONB would be the better long-term type, but every read site does
--     JSON.parse() on a string. Changing it is a separate commit.
--
--   id is GENERATED BY DEFAULT AS IDENTITY, not ALWAYS.
--     BY DEFAULT permits the data-migration script to insert explicit primary
--     keys, which is required to preserve user_games.user_id references from the
--     old database. The sequence is resynchronised afterwards.

CREATE TABLE IF NOT EXISTS users (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username           TEXT UNIQUE NOT NULL,
  -- NULL is legitimate and expected: LDAP users authenticate against the
  -- directory and never have a local bcrypt hash. Do not add NOT NULL.
  password           TEXT,
  can_create_users   INTEGER NOT NULL DEFAULT 0,
  can_manage_users   INTEGER NOT NULL DEFAULT 0,
  email              TEXT,
  ntfy_url           TEXT,
  ntfy_topic         TEXT,
  gotify_url         TEXT,
  gotify_token       TEXT,
  telegram_chat_id   TEXT,
  created_at         TEXT,
  origin             TEXT NOT NULL DEFAULT 'local',
  display_name       TEXT,
  shares_library     INTEGER NOT NULL DEFAULT 0,
  notification_days  TEXT DEFAULT '[0,7,30]'
);

CREATE TABLE IF NOT EXISTS user_games (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- TEXT. See the note above. This is the single most important line in the file.
  game_id             TEXT NOT NULL,
  game_name           TEXT,
  cover_url           TEXT,
  release_date        TEXT,
  status              TEXT,
  steam_app_id        TEXT,
  last_price          TEXT,
  last_price_updated  TEXT,
  crack_status        TEXT,
  backlog_order       INTEGER,
  UNIQUE (user_id, game_id)
);

-- Keyed on username, matching the original. Re-keying to users.id is a genuine
-- improvement (a recreated account currently inherits a deleted one's shares)
-- but it changes every share query, so it is deliberately NOT bundled into this
-- mechanical port. Tracked as follow-up work.
--
-- ON DELETE CASCADE is new and is a safety fix, not a behaviour change: SQLite
-- declared these foreign keys but ran with PRAGMA foreign_keys OFF, so deleting
-- a user left dangling share rows behind. Production currently contains exactly
-- that kind of debris.
CREATE TABLE IF NOT EXISTS user_shares (
  from_user  TEXT NOT NULL REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE,
  to_user    TEXT NOT NULL REFERENCES users(username) ON DELETE CASCADE ON UPDATE CASCADE,
  shared_at  TEXT,
  PRIMARY KEY (from_user, to_user)
);

-- Indexes for the actual hot paths.
-- The library list is always "every game for one user", and the notification
-- cron scans by release_date. Neither had an index under SQLite.
CREATE INDEX IF NOT EXISTS idx_user_games_user_id      ON user_games (user_id);
CREATE INDEX IF NOT EXISTS idx_user_games_release_date ON user_games (release_date);
CREATE INDEX IF NOT EXISTS idx_user_shares_to_user     ON user_shares (to_user);
