-- Personal access tokens: a credential a NON-INTERACTIVE client can hold.
--
-- Today the only way to call this API is a 12-hour JWT obtained by posting a
-- username and password. That forces every script — and the planned MCP server —
-- to store the owner's actual password and re-login when the token expires. The
-- obvious "fix" is a longer JWT, and it is the wrong one: a JWT is self-describing,
-- so the only ways to revoke one are rotating JWT_SECRET, which signs every session
-- out including the web app and the phone, or deleting the account. That is a
-- demolition charge, not a lever.
--
-- A token that is LOOKED UP can be revoked by deleting one row. That is the entire
-- reason this is a table rather than a longer expiry.
--
-- WHY LONG-LIVED CREDENTIALS ARE SAFE HERE SPECIFICALLY: the usual objection is that
-- a long-lived token freezes privilege at the moment it was issued. That does not
-- apply, because authRequired re-reads can_manage_users from `users` on every single
-- request and 401s when the row is gone. Demote or delete an account and its tokens
-- stop working on the next call. This design is only available because that decision
-- was already taken.

CREATE TABLE IF NOT EXISTS api_tokens (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- CASCADE so revocation cannot be forgotten: deleting a user must not leave
  -- credentials behind that authenticate as them. user_shares already relies on
  -- cascade for the same reason.
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,

  -- Operator-facing label ("laptop cli", "mcp"). The only way to tell two tokens
  -- apart in a revocation list, since the secret itself is never shown again.
  name         TEXT NOT NULL,

  -- SHA-256 hex of the token, never the token. UNIQUE because it is the lookup key
  -- on every authenticated request, and the unique index is what makes that lookup
  -- an index probe rather than a scan.
  --
  -- SHA-256 rather than bcrypt is deliberate and is NOT the usual password mistake.
  -- bcrypt exists to make guessing a LOW-ENTROPY human-chosen secret expensive.
  -- These are 256 bits from a CSPRNG: there is no dictionary to slow down, and a
  -- work factor here would instead add ~100ms to every API call, which is a
  -- self-inflicted denial of service on the hot path.
  token_hash   TEXT NOT NULL UNIQUE,

  -- JSON array, same convention as users.notification_days. Two scopes only:
  -- 'library' and 'admin'. A 42-route scope matrix for a single-user instance would
  -- need its own CI gate to stay honest; the only boundary that actually matters is
  -- "the MCP cannot create users or read API keys".
  --
  -- Scopes may only ever NARROW what the account can do — see services/auth.js.
  scopes       TEXT NOT NULL DEFAULT '["library"]',

  created_at   TEXT NOT NULL,

  -- Advisory. Lets an operator spot a token nothing uses before revoking it, which
  -- is the difference between confident cleanup and leaving it "just in case".
  last_used_at TEXT,

  -- NULL means no expiry. Deliberate: the point of this table is that revocation is
  -- a DELETE, so an expiry is an optional extra rather than the safety mechanism.
  expires_at   TEXT
);

-- Listing and revoking a user's tokens, and the cascade on user deletion.
CREATE INDEX IF NOT EXISTS idx_api_tokens_user ON api_tokens(user_id);
