-- WHEN a status changed, which nothing has ever recorded.
--
-- `status` on user_games is current state. Five statements write it (all in
-- services/library.js: the upsert, setStatus's two branches, promoteReleased, and the
-- metadata refresh) and every one of them discards the previous value on commit. So
-- "how many games did I finish in March" and "how long did that take" are not slow
-- queries today, they are unanswerable.
--
-- A TABLE, NOT COLUMNS ON user_games. Three reasons, each independently sufficient:
--
--   1. GET /api/user/:username/games is `SELECT *` (services/library.js#listGamesWithAliases),
--      so any new column on that table silently enters a FROZEN v1 response. That has
--      already happened once: 004's added_at is on the wire today, and
--      test/api-contract.test.js did not catch it because it asserts key equality
--      against a hand-built literal rather than a real row.
--   2. A `done_at` column answers "when did this last become done" and nothing else.
--      Not how many times, not how long it sat in `playing`, not whether it is still
--      done. It is also destroyed by the next transition, so the one event worth
--      keeping is the one a column cannot keep.
--   3. It cannot record WHO. See `source` below — that column is the whole point.
--
-- DELIBERATELY NOT SEEDED, and this is 004's argument applied unchanged: there is no
-- honest changed_at for the 188 existing rows. added_at is NULL for everything
-- predating 004 and, where present, means "added", not "finished". Writing
-- to_status = current status would claim every game reached its status on the day this
-- migration ran — false for all of them, and indistinguishable from a real value
-- forever after. The resolution is architectural rather than a data hack: current
-- state is read from user_games, which is authoritative; change over time is read from
-- this table, which starts empty and is honest about it. The statistics page states
-- its own coverage rather than implying the gap is zero.

CREATE TABLE IF NOT EXISTS user_game_status_events (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- CASCADE, matching user_games (001) and api_tokens (003): deleting an account must
  -- not leave its history behind.
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,

  -- TEXT. 'igdb_12345', never a number — the same rule as user_games.game_id.
  --
  -- NO foreign key to user_games, and that is deliberate rather than an omission. A
  -- composite FK on (user_id, game_id) is available — 001 provides the UNIQUE — and
  -- would cascade this history away when a game is removed from the library. "I
  -- finished 12 games this year" must not become 11 because one was tidied up. The
  -- cost is that a removed game's events cannot be joined to a game_name and render as
  -- a bare id; accepted, rather than copying the name into every row where it would go
  -- stale on the first metadata refresh.
  game_id      TEXT NOT NULL,

  -- NULL means the row did not exist before this event, i.e. the game was added.
  --
  -- The IS NULL disjunct is MANDATORY. 002's header records why: the column is
  -- nullable, a CHECK that omits the disjunct rejects every such row, and
  -- schema-migrate.js is fatal on error — a wrong CHECK here does not degrade the
  -- feature, it takes the backend down on the next boot.
  from_status  TEXT
               CHECK (from_status IS NULL
                      OR from_status IN ('wishlist','playing','done','backlog','unreleased')),

  -- The same five values 002 pinned on user_games.status, enumerated again here for
  -- 002's stated reason: the allowlist belongs in the DATA, not only in whichever
  -- function currently remembers it.
  to_status    TEXT NOT NULL
               CHECK (to_status IN ('wishlist','playing','done','backlog','unreleased')),

  -- TIMESTAMPTZ, not the TEXT that user_games uses for dates.
  --
  -- 001 keeps dates as TEXT because the SPA and the Android client already consume
  -- them as ISO strings. That argument does not apply to a table with no existing
  -- clients, and schema_migrations.applied_at already sets the TIMESTAMPTZ precedent.
  -- It makes date_trunc and range predicates work without string-collation games. The
  -- pg driver returns a JS Date, which JSON.stringify renders as the same ISO 8601
  -- string, so nothing on the wire changes — but a mapper must convert it explicitly
  -- rather than assume.
  changed_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- WHO caused it, and the reason a denormalised done_at cannot do this job.
  --
  --   user             a person chose this status — the v1 upsert, v2's PATCH, v2's add
  --   release_sweep    the 08:00 cron, /api/admin/check-releases, the v2 job, or
  --                    run_notifications.js promoted unreleased -> wishlist because a
  --                    date passed. NOBODY DID ANYTHING. There are 58 unreleased games
  --                    in one library today, so a single nightly run would otherwise
  --                    post the largest number on the statistics page.
  --   metadata_refresh a provider's release date moved and the status was re-synced to
  --                    it. The user asked for a refresh; the machine picked the status.
  --                    Neither of the above, so neither label fits.
  --   backfill         reserved. Nothing writes it (see the no-seed note above); it
  --                    exists so that if an import is ever added, imported rows are
  --                    distinguishable from observed ones at a glance instead of by
  --                    archaeology.
  --
  -- Every "achievement" query filters source = 'user'. The rest is provenance, kept
  -- because dropping it would leave the log unable to explain its own row counts.
  source       TEXT NOT NULL
               CHECK (source IN ('user','release_sweep','metadata_refresh','backfill'))

  -- No UNIQUE constraint anywhere: done -> playing -> done is a legitimate sequence
  -- and must produce two 'done' rows, not one.
);

-- "How many transitions to `done` for user U between A and B", and the GROUP BY
-- date_trunc over the same range. Equality, equality, range — the column order is the
-- query.
CREATE INDEX IF NOT EXISTS idx_uge_user_status_time
  ON user_game_status_events (user_id, to_status, changed_at);

-- "How long did game G take" — one game's timeline in order. A different leading
-- column set, so it is a different index; the one above cannot serve this without
-- scanning every status the user has ever set.
CREATE INDEX IF NOT EXISTS idx_uge_user_game_time
  ON user_game_status_events (user_id, game_id, changed_at);
